[package]
name = "perlin_trick"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "0.3.4"
lazy_static = "1.4.0"
noise = "0.8.2"
rand = "0.8.5"
